version: '3'
services:

  backend:
    build: backend
    ports:
      - 8080:8080
    command: java -jar /app.jar

  frontend:
    build: frontend
    ports:
      - 8081:8081
    volumes:
      - ./frontend:/app
    command: npx expo start --tunnel
    stdin_open: true # docker run -i
    tty: true        # docker run -t
# volumes:
#   nmhsapp:
    # expose:
    #   - 

  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - ./conf/:/etc/nginx/conf.d
  #     - /data/certbot/conf:/etc/letsencrypt
  #     - /data/certbot/www:/var/www/certbot
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - backend
  #     - frontend